name: _update-api
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run api:update
      - uses: tibdex/github-app-token@v1
        if: ${{ !env.ACT }}
        id: create-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        with:
          repository-name: iptv-org/api
          branch: gh-pages
          folder: .gh-pages/api
          token: ${{ steps.create-app-token.outputs.token }}
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to GitHub Pages'
          clean: false
